### ISSUE TITLE
Issues that are there in parsing the incoming data buffer.

### ISSUE THREAD

**Issue by mattipr** [jeremyko/nodeChatServer#1]
Thanks for the .on(data) method which I am using in one of my projects. I noticed a few issues and wanted to confirm the same as I am making these changes in my project. Issues are as follows: (all the questions are inside the .on(data) function so you can just search for the string)

-> Your code
if( recvedThisTimeLen < packetHeaderLen )  
->correct code
if (accumulatingLen < packetHeaderLen)

-> Your code
else if( recvedThisTimeLen == packetHeaderLen ) {
->correct code
else if (accumulatingLen === PACKETHEADERLEN)

->Your code
var newBufRebuild = new Buffer( accumulatingBuffer.length );
->correct code
var newBufRebuild = new Buffer(accumulatingBuffer.length - (totalPacketLen + PACKETHEADERLEN));

Please let me know if this is right.

**Comment by jeremyko** [comment]
yes ,you're definitely right,  i'll fix that. thanks!
